[package]
name = "rusty-git"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.2", features = ["derive"] }
color-eyre = "0.6.2"
eyre = "0.6.12"

# always compile `backtrace` with release optimizations to get decent dev
# performance out of `color-eyre`
[profile.dev.package.backtrace]
opt-level = 3
